### PR TITLE
chore: add star history chart badge

### PR DESCRIPTION
**Pull request by katcipis**
# Reason for This Change

Star history is cool :-).

## Description of Changes

Added the badge.

### CODE REVIEW

**Review by soerenmartius — APPROVED** [review]
yayyyy !

**Review by i4ki — DISMISSED** [review]
:rocket:

**Review by soerenmartius — CHANGES_REQUESTED** [review]
Let's put this maybe a bit further down as at the moment it's render right at the top of the repo?

**Comment by katcipis** [comment]
> Let's put this maybe a bit further down as at the moment it's render right at the top of the repo?

Sorry I thought this was a badge with the link to see the graph :laughing:

**Review by soerenmartius — APPROVED** [review]
lgtm

**Pull request merged**
