### PR TITLE
chore: use GoReleaser for announcing releases on twitter

### PR DESCRIPTION
**Pull request by i4ki**
# Reason for This Change

Make use of goreleaser to announce the release in the same GHA workflow.

@soerenmartius can you set up the secrets below?

```
TWITTER_CONSUMER_KEY
TWITTER_CONSUMER_SECRET
TWITTER_ACCESS_TOKEN
TWITTER_ACCESS_TOKEN_SECRET
```
docs: https://goreleaser.com/customization/announce/twitter/

### CODE REVIEW

**Review by soerenmartius — APPROVED** [review]
LGTM!

but don't we need to configure the Twitter credentials somehow?

**Comment by soerenmartius** [comment]
@i4ki the secrets are already created:

- `TWITTER_MINEIROS_IO_ACCESS_TOKEN_SECRET`
- `TWITTER_MINEIROS_IO_ACCESS_TOKEN_KEY`
- `TWITTER_APP_TERRAMATE_RELEASE_CONSUMER_API_KEY_SECRET`
- `TWITTER_APP_TERRAMATE_RELEASE_CONSUMER_API_KEY`

can we use the existing ones?

**Comment by i4ki** [comment]
yep, will update the env in the workflow. Thanks

**Review by mariux — APPROVED** [review]
lgtm

**Review by soerenmartius — APPROVED** [review]
lgtm! great job

**Pull request merged**
